export type SourceCategory =
  | 'framework'
  | 'build-tool'
  | 'language-runtime'
  | 'css-styling'
  | 'testing'
  | 'web-platform'
  | 'person-blog'
  | 'general';

export interface Source {
  id: string;
  name: string;
  category: SourceCategory;
  tags: string[];
  feedUrl: string | null;
  homeUrl: string;
  authorName?: string;
}

export const sources: Source[] = [
  // Frameworks / Libraries
  {
    id: 'react-releases',
    name: 'React Releases',
    category: 'framework',
    tags: ['react', 'release'],
    feedUrl: 'https://github.com/facebook/react/releases.atom',
    homeUrl: 'https://react.dev',
  },
  {
    id: 'vuejs-blog',
    name: 'Vue.js Blog',
    category: 'framework',
    tags: ['vue', 'frameworks'],
    feedUrl: 'https://blog.vuejs.org/feed.rss',
    homeUrl: 'https://blog.vuejs.org',
  },
  {
    id: 'angular-blog',
    name: 'Angular Blog',
    category: 'framework',
    tags: ['angular', 'frameworks'],
    feedUrl: 'https://blog.angular.dev/feed',
    homeUrl: 'https://blog.angular.dev',
  },
  {
    id: 'svelte-releases',
    name: 'Svelte Releases',
    category: 'framework',
    tags: ['svelte', 'release'],
    feedUrl: 'https://github.com/sveltejs/svelte/releases.atom',
    homeUrl: 'https://svelte.dev',
  },
  {
    id: 'solidjs-releases',
    name: 'SolidJS Releases',
    category: 'framework',
    tags: ['solidjs', 'release'],
    feedUrl: 'https://github.com/solidjs/solid/releases.atom',
    homeUrl: 'https://solidjs.com',
  },
  {
    id: 'astro-blog',
    name: 'Astro Blog',
    category: 'framework',
    tags: ['astro', 'frameworks'],
    feedUrl: 'https://astro.build/rss.xml',
    homeUrl: 'https://astro.build/blog',
  },
  {
    id: 'qwik-releases',
    name: 'Qwik Releases',
    category: 'framework',
    tags: ['frameworks', 'release'],
    feedUrl: 'https://github.com/QwikDev/qwik/releases.atom',
    homeUrl: 'https://qwik.dev',
  },
  {
    id: 'nextjs-blog',
    name: 'Next.js Blog',
    category: 'framework',
    tags: ['react', 'frameworks'],
    feedUrl: 'https://nextjs.org/feed.xml',
    homeUrl: 'https://nextjs.org/blog',
  },
  {
    id: 'nuxt-releases',
    name: 'Nuxt Releases',
    category: 'framework',
    tags: ['vue', 'frameworks', 'release'],
    feedUrl: 'https://github.com/nuxt/nuxt/releases.atom',
    homeUrl: 'https://nuxt.com',
  },
  {
    id: 'remix-blog',
    name: 'Remix Blog',
    category: 'framework',
    tags: ['react', 'frameworks'],
    feedUrl: 'https://remix.run/blog/rss.xml',
    homeUrl: 'https://remix.run/blog',
  },
  {
    id: 'tanstack-blog',
    name: 'TanStack Blog',
    category: 'framework',
    tags: ['react', 'frameworks', 'dx'],
    feedUrl: 'https://tanstack.com/rss.xml',
    homeUrl: 'https://tanstack.com',
  },

  // Build Tools
  {
    id: 'vite-blog',
    name: 'Vite Blog',
    category: 'build-tool',
    tags: ['tooling', 'build-tools'],
    feedUrl: 'https://github.com/vitejs/vite/releases.atom',
    homeUrl: 'https://vite.dev',
  },
  {
    id: 'vite-releases',
    name: 'Vite Releases',
    category: 'build-tool',
    tags: ['tooling', 'build-tools', 'release'],
    feedUrl: 'https://vite.dev/blog.rss',
    homeUrl: 'https://vite.dev',
  },
  {
    id: 'voidzero-blog',
    name: 'VoidZero Blog',
    category: 'build-tool',
    tags: ['tooling', 'build-tools'],
    feedUrl: 'https://voidzero.dev/feed.xml',
    homeUrl: 'https://voidzero.dev',
  },
  {
    id: 'rollup-releases',
    name: 'Rollup Releases',
    category: 'build-tool',
    tags: ['tooling', 'build-tools', 'release'],
    feedUrl: 'https://github.com/rollup/rollup/releases.atom',
    homeUrl: 'https://rollupjs.org',
  },
  {
    id: 'esbuild-releases',
    name: 'esbuild Releases',
    category: 'build-tool',
    tags: ['tooling', 'build-tools', 'release', 'performance'],
    feedUrl: 'https://github.com/evanw/esbuild/releases.atom',
    homeUrl: 'https://esbuild.github.io',
  },
  {
    id: 'bun-blog',
    name: 'Bun Blog',
    category: 'build-tool',
    tags: ['bun', 'tooling', 'build-tools'],
    feedUrl: 'https://bun.sh/rss.xml',
    homeUrl: 'https://bun.sh/blog',
  },
  {
    id: 'biome-blog',
    name: 'Biome Blog',
    category: 'build-tool',
    tags: ['tooling', 'dx'],
    feedUrl: 'https://biomejs.dev/blog/rss.xml',
    homeUrl: 'https://biomejs.dev/blog',
  },
  {
    id: 'pnpm-releases',
    name: 'pnpm Releases',
    category: 'build-tool',
    tags: ['tooling', 'release'],
    feedUrl: 'https://github.com/pnpm/pnpm/releases.atom',
    homeUrl: 'https://pnpm.io',
  },
  {
    id: 'github-blog',
    name: 'GitHub Blog',
    category: 'build-tool',
    tags: ['tooling', 'dx'],
    feedUrl: 'https://github.blog/feed',
    homeUrl: 'https://github.blog',
  },

  // Languages / Runtimes
  {
    id: 'typescript-blog',
    name: 'TypeScript Blog',
    category: 'language-runtime',
    tags: ['typescript'],
    feedUrl: 'https://devblogs.microsoft.com/typescript/feed/',
    homeUrl: 'https://devblogs.microsoft.com/typescript',
  },
  {
    id: 'nodejs-blog',
    name: 'Node.js Blog',
    category: 'language-runtime',
    tags: ['nodejs'],
    feedUrl: 'https://nodejs.org/en/feed/blog.xml',
    homeUrl: 'https://nodejs.org/en/blog',
  },
  {
    id: 'deno-releases',
    name: 'Deno Releases',
    category: 'language-runtime',
    tags: ['deno', 'release'],
    feedUrl: 'https://github.com/denoland/deno/releases.atom',
    homeUrl: 'https://deno.com',
  },
  {
    id: 'wasm-blog',
    name: 'WebAssembly Blog',
    category: 'language-runtime',
    tags: ['wasm', 'web-platform'],
    feedUrl: 'https://webassembly.org/feed.xml',
    homeUrl: 'https://webassembly.org/blog',
  },

  // CSS / Styling
  {
    id: 'tailwind-blog',
    name: 'Tailwind CSS Blog',
    category: 'css-styling',
    tags: ['css', 'tooling'],
    feedUrl: 'https://tailwindcss.com/feeds/feed.xml',
    homeUrl: 'https://tailwindcss.com/blog',
  },
  {
    id: 'postcss-releases',
    name: 'PostCSS Releases',
    category: 'css-styling',
    tags: ['css', 'tooling', 'release'],
    feedUrl: 'https://github.com/postcss/postcss/releases.atom',
    homeUrl: 'https://postcss.org',
  },
  {
    id: 'lightningcss-releases',
    name: 'Lightning CSS Releases',
    category: 'css-styling',
    tags: ['css', 'tooling', 'build-tools', 'release'],
    feedUrl: 'https://github.com/parcel-bundler/lightningcss/releases.atom',
    homeUrl: 'https://lightningcss.dev',
  },
  {
    id: 'csswg-blog',
    name: 'CSS Working Group Blog',
    category: 'css-styling',
    tags: ['css', 'web-platform'],
    feedUrl: 'https://www.w3.org/blog/CSS/feed/',
    homeUrl: 'https://www.w3.org/blog/CSS',
  },

  // Testing
  {
    id: 'vitest-releases',
    name: 'Vitest Releases',
    category: 'testing',
    tags: ['testing', 'release'],
    feedUrl: 'https://github.com/vitest-dev/vitest/releases.atom',
    homeUrl: 'https://vitest.dev',
  },
  {
    id: 'playwright-releases',
    name: 'Playwright Releases',
    category: 'testing',
    tags: ['testing', 'release'],
    feedUrl: 'https://github.com/microsoft/playwright/releases.atom',
    homeUrl: 'https://playwright.dev',
  },
  {
    id: 'cypress-blog',
    name: 'Cypress Blog',
    category: 'testing',
    tags: ['testing'],
    feedUrl: 'https://www.cypress.io/blog/rss.xml',
    homeUrl: 'https://www.cypress.io/blog',
  },
  {
    id: 'jest-releases',
    name: 'Jest Releases',
    category: 'testing',
    tags: ['testing', 'release'],
    feedUrl: 'https://github.com/jestjs/jest/releases.atom',
    homeUrl: 'https://jestjs.io',
  },

  // Web Platform / Browsers
  {
    id: 'chrome-developers',
    name: 'Chrome Developers',
    category: 'web-platform',
    tags: ['browser', 'web-platform'],
    feedUrl: null,
    homeUrl: 'https://developer.chrome.com/blog',
  },
  {
    id: 'web-dev',
    name: 'web.dev',
    category: 'web-platform',
    tags: ['web-platform', 'performance', 'accessibility'],
    feedUrl: 'https://web.dev/feed.xml',
    homeUrl: 'https://web.dev',
  },
  {
    id: 'mdn-blog',
    name: 'MDN Blog',
    category: 'web-platform',
    tags: ['web-platform', 'browser', 'html'],
    feedUrl: 'https://developer.mozilla.org/en-US/blog/rss.xml',
    homeUrl: 'https://developer.mozilla.org/en-US/blog',
  },
  {
    id: 'firefox-blog',
    name: 'Firefox Hacks',
    category: 'web-platform',
    tags: ['browser', 'web-platform'],
    feedUrl: 'https://hacks.mozilla.org/feed/',
    homeUrl: 'https://hacks.mozilla.org',
  },
  {
    id: 'webkit-blog',
    name: 'WebKit Blog',
    category: 'web-platform',
    tags: ['browser', 'web-platform'],
    feedUrl: 'https://webkit.org/feed/',
    homeUrl: 'https://webkit.org/blog',
  },
  {
    id: 'tc39-proposals',
    name: 'TC39 Proposals (commits)',
    category: 'web-platform',
    tags: ['javascript', 'web-platform'],
    feedUrl: 'https://github.com/tc39/proposals/commits.atom',
    homeUrl: 'https://github.com/tc39/proposals',
  },

  // Influential People
  {
    id: 'overreacted',
    name: 'Overreacted',
    category: 'person-blog',
    tags: ['react', 'javascript'],
    feedUrl: 'https://overreacted.io/rss.xml',
    homeUrl: 'https://overreacted.io',
    authorName: 'Dan Abramov',
  },
  {
    id: 'antfu-blog',
    name: 'Anthony Fu Blog',
    category: 'person-blog',
    tags: ['vue', 'tooling', 'javascript'],
    feedUrl: 'https://antfu.me/feed.xml',
    homeUrl: 'https://antfu.me',
    authorName: 'Anthony Fu',
  },
  {
    id: 'joshwcomeau',
    name: 'Josh W. Comeau',
    category: 'person-blog',
    tags: ['css', 'react', 'tutorial'],
    feedUrl: 'https://www.joshwcomeau.com/rss.xml',
    homeUrl: 'https://www.joshwcomeau.com',
    authorName: 'Josh W. Comeau',
  },
  {
    id: 'total-typescript',
    name: 'Total TypeScript',
    category: 'person-blog',
    tags: ['typescript', 'tutorial'],
    feedUrl: 'https://www.totaltypescript.com/rss.xml',
    homeUrl: 'https://www.totaltypescript.com',
    authorName: 'Matt Pocock',
  },
  {
    id: 'kentcdodds',
    name: 'Kent C. Dodds',
    category: 'person-blog',
    tags: ['react', 'testing', 'javascript'],
    feedUrl: 'https://kentcdodds.com/blog/rss.xml',
    homeUrl: 'https://kentcdodds.com/blog',
    authorName: 'Kent C. Dodds',
  },
  {
    id: 'jake-archibald',
    name: 'Jake Archibald',
    category: 'person-blog',
    tags: ['web-platform', 'javascript', 'performance'],
    feedUrl: 'https://jakearchibald.com/posts.rss',
    homeUrl: 'https://jakearchibald.com',
    authorName: 'Jake Archibald',
  },
  {
    id: 'addy-osmani',
    name: 'Addy Osmani',
    category: 'person-blog',
    tags: ['performance', 'javascript'],
    feedUrl: 'https://addyosmani.com/rss.xml',
    homeUrl: 'https://addyosmani.com',
    authorName: 'Addy Osmani',
  },
  {
    id: 'una-kravets',
    name: 'Una Kravets',
    category: 'person-blog',
    tags: ['css', 'web-platform', 'design'],
    feedUrl: 'https://una.im/rss.xml',
    homeUrl: 'https://una.im',
    authorName: 'Una Kravets',
  },
  {
    id: 'lee-robinson',
    name: 'Lee Robinson',
    category: 'person-blog',
    tags: ['react', 'frameworks'],
    feedUrl: null,
    homeUrl: 'https://leerob.com',
    authorName: 'Lee Robinson',
  },
  {
    id: 'rich-harris',
    name: 'Rich Harris',
    category: 'person-blog',
    tags: ['svelte', 'frameworks'],
    feedUrl: null,
    homeUrl: 'https://github.com/Rich-Harris',
    authorName: 'Rich Harris',
  },

  // General Web Dev
  {
    id: 'css-tricks',
    name: 'CSS-Tricks',
    category: 'general',
    tags: ['css', 'javascript', 'tutorial'],
    feedUrl: 'https://css-tricks.com/feed/',
    homeUrl: 'https://css-tricks.com',
  },
  {
    id: 'smashing-magazine',
    name: 'Smashing Magazine',
    category: 'general',
    tags: ['design', 'css', 'javascript', 'tutorial'],
    feedUrl: 'https://www.smashingmagazine.com/feed/',
    homeUrl: 'https://www.smashingmagazine.com',
  },
  {
    id: 'a-list-apart',
    name: 'A List Apart',
    category: 'general',
    tags: ['design', 'accessibility', 'web-platform'],
    feedUrl: 'https://alistapart.com/main/feed/',
    homeUrl: 'https://alistapart.com',
  },
  {
    id: 'js-weekly',
    name: 'JavaScript Weekly',
    category: 'general',
    tags: ['javascript', 'typescript'],
    feedUrl: 'https://javascriptweekly.com/rss/',
    homeUrl: 'https://javascriptweekly.com',
  },
  {
    id: 'this-week-in-react',
    name: 'This Week in React',
    category: 'general',
    tags: ['react', 'frameworks'],
    feedUrl: 'https://thisweekinreact.com/newsletter/rss.xml',
    homeUrl: 'https://thisweekinreact.com',
  },
];
